# ~/.zshrc
# Zsh configuration file

# Path to your oh-my-zsh installation (if using oh-my-zsh)
# export ZSH="$HOME/.oh-my-zsh"

# Set Homebrew path (Apple Silicon)
if [[ $(uname -m) == "arm64" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Environment variables
export EDITOR='vim'
export VISUAL='vim'

# Aliases
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'

# Directory navigation
alias projects='cd ~/Projects'
alias desktop='cd ~/Desktop'

# Homebrew
alias brewup='brew update && brew upgrade && brew cleanup'

# FZF configuration (if installed)
if command -v fzf &> /dev/null; then
    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
fi

# History configuration
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

# Enable color support
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# Custom prompt (simple)
PROMPT='%F{blue}%~%f %F{green}❯%f '
