# ~/.zshrc
# Zsh configuration file

# Path to your oh-my-zsh installation (if using oh-my-zsh)
# export ZSH="$HOME/.oh-my-zsh"

# Set Homebrew path (Apple Silicon)
if [[ $(uname -m) == "arm64" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Environment variables
export EDITOR='nano'
export VISUAL='nano'

# Aliases
alias ..='cd ..'
alias ...='cd ../..'

# Homebrew
alias brewup='brew update && brew upgrade && brew cleanup'

# History configuration
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

# Enable color support
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# Custom prompt (simple)
PROMPT='%F{blue}%~%f %F{green}❯%f '
